### ISSUE TITLE
About label file

### ISSUE THREAD

**Issue by mrsempress** [LCAD-UFES/publications-arruda-ijcnn-2019#1]
In berkeley, I only find `bdd100k_labels_release.zip`, and it has two files `bdd100k_labels_images_train.json`, `bdd100k_labels_images_val.json`. So, in `filter_dataset.py` line 45, it can't find the label_train_dir/xxxx.json.
Can you share the bdd100k_labels.zip, or maybe change the code?
Thanks.

**Comment by viniciusarruda** [comment]
I noted that the label format changed. The source code provided here was done for the previous format.
Unfortunately, while updating the `filter_dataset.py` code, I found missing labels in the new format and already opened an [issue](https://github.com/ucbdrive/bdd-data/issues/60).
For while, I shared [here](https://drive.google.com/drive/folders/1D6h5GGaaT8Dja8sH8jZVoaSCm53XTKFJ?usp=sharing) the processed images with its labels that was used in the paper.

**Comment by mrsempress** [comment]
> I noted that the label format changed. The source code provided here was done for the previous format.
> Unfortunately, while updating the `filter_dataset.py` code, I found missing labels in the new format and already opened an [issue](https://github.com/ucbdrive/bdd-data/issues/60).
> For while, I shared [here](https://drive.google.com/drive/folders/1D6h5GGaaT8Dja8sH8jZVoaSCm53XTKFJ?usp=sharing) the processed images with its labels that was used in the paper.

Thanks~
